### PR TITLE
Fix `node 6` errors

### PR DESCRIPTION
**Pull request by emilio-martinez**
**fix(install): allow smooth install on `node 6 (LTS)`**

Fixes getting `Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/darwin-x64-48_binding.node”` while executing `npm install` on `node 6 (LTS)`.

The url mentioned in the error in fact doesn’t exist because `node-sass 3.4.2` supports up to `node 5`, meaning that the binaries at the time ony went up to `…/v3.4.2/darwin-x64-47_binding.node`. Not being aware of the history around why `node-sass` as a dependency was capped at that specific version, I upgraded to `node-sass ~3.13.0` which supports `node 6` and `libSass 3.3.6` (up from `libSass 3.3.2`)—what I would consider a sensible upgrade.

**fix(test): add `node 6` support for tests**

The version of `lab` stated in the devDependencies did not support `node 6`. Running the tests would throw an error of `The following leaks were detected:Reflect`. On `lab 10.3.2`, `node 6` support is added and `Reflect` is added to the globals whitelist, fixing that error (see hapijs/lab#568).

Upgrading `lab` and `code` to their latest major versions.

### CODE REVIEW

**Comment by emilio-martinez** [comment]
@mcampa Rebased. Please review and let me know your thoughts. Thank you!

**Comment by mcampa** [comment]
Hi @emilio-martinez, thanks for your contribution.  The problem is that `libSass 3.3.6` is not compatible with our themes. The breaking change was introduced in [libSass 3.3.3](https://github.com/sass/libsass/releases/tag/3.3.3)

You can read more about it [here](https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.2dyx8f6ds)

We are currently working in a "possible" solution that consist in replacing node-sass with a pure javascript alternative

If you have an idea, or any thought about this issue please let me know

**Comment by emilio-martinez** [comment]
@mcampa from what I'm reading, it looks like "conditionally defining mixins, functions and imports" is the breaking change that was introduced back then, correct? If so, do you have an example of where it happens on this or another of the BigCommerce codebases? If I can wrap my head around it, I could look into helping with a PR.

**Comment by mcampa** [comment]
The incompatibility happens in [Cornerstone](https://github.com/bigcommerce/stencil) theme and most of our theme in the marketplace. But the main problem is custom themes already in production used by our merchants. Until we find a solution on how to migrate all those themes, we have to stay with `LibSass 3.3.2`.

I'm investigating on a possible solution using [sass.js](https://github.com/medialize/sass.js)

**Comment by emilio-martinez** [comment]
Ouch! 3.2MB (670KB gzipped). I can see why they nudge people towards `node-sass` anyway. Wouldn't `sass.js` have the same issues given that the breaking change is on `Libsass`?

Presumably people forked or clones Cornerstone and built from there, correct? (I don't know the common development patterns; I just know what we did internally where I work) I would think that they wouldn't have any issues building unless they upgrade dependencies; however, that would be "easily" resolved by bumping Cornerstone a major version to indicate the breaking change, no?

**Comment by mcampa** [comment]
The size doesn't really matter because the code runs in the server. 

I forked `sass.js` and compiled it with `libsass 3.3.2` and it kind of works, but the main problem is that is slow.

**Comment by mattolson** [comment]
The latest version (1.0.6) now works with Node 6.

**Pull request closed without merging**
